### ISSUE TITLE
Add "You might also like" section at the end of each article

### ISSUE THREAD

**Issue by AurelienGasser** [AurelienGasser/planetocd#16]
It should display a link to another random article

**Comment by toshitapandey** [comment]
@AurelienGasser - can i pick this up?

**Comment by AurelienGasser** [comment]
@toshitapandey Absolutely, go ahead. Thank you!

**Comment by AurelienGasser** [comment]
@toshitapandey I just wanted to let you know that I [bumped the ruby version](https://github.com/AurelienGasser/planetocd/commit/3ba4a74d3d499e1fc6c8f205fe62dc8e4341c585) of the project from `2.5.1` to `2.6.5`. I also wrote some [instructions on how to run the project locally](https://github.com/AurelienGasser/planetocd/blob/master/run_local.md). Please let me know if I can be of any help! :)

**Comment by AurelienGasser** [comment]
@toshitapandey are you still working on this?

**Comment by toshitapandey** [comment]
Yes.

Thanks and regards,
Toshita Pandey
Developer by profession, writer by passion!!
