### ISSUE TITLE
Add "this article helped me" button at the end of each article

### ISSUE THREAD

**Issue by AurelienGasser** [AurelienGasser/planetocd#17]
Make it create a database entry with 

- Timestamp
- IP Address
- User Agent
- Article id

**Comment by andersonfernandes** [comment]
Hi @AurelienGasser I can work on this issue if it's ok to you

**Comment by AurelienGasser** [comment]
@andersonfernandes absolutely, go ahead!

**Comment by AurelienGasser** [comment]
@andersonfernandes I just wanted to let you know that I [bumped the ruby version](https://github.com/AurelienGasser/planetocd/commit/3ba4a74d3d499e1fc6c8f205fe62dc8e4341c585) of the project from `2.5.1` to `2.6.5`. I also wrote some [instructions on how to run the project locally](https://github.com/AurelienGasser/planetocd/blob/master/run_local.md). Please let me know if I can be of any help! :)

**Comment by andersonfernandes** [comment]
Thank you @AurelienGasser. I'm almost finishing the implementation, and soon a PR will be created.

**Comment by AurelienGasser** [comment]
Fixed by https://github.com/AurelienGasser/planetocd/pull/22
