### ISSUE TITLE
Add pagination to main list of articles

### ISSUE THREAD

**Issue by AurelienGasser** [AurelienGasser/planetocd#38]
Add pagination to e.g. https://planetocd.org/es

The pagination component from the article page can be reused, e.g. https://planetocd.org/es/articles/1/obsesion-religiosa-cuando-el-toc-se-mezcla-con-la-religion-y-la-fe

**Comment by Jamme-D** [comment]
Hey, I'm new to open source. I think you have a really interesting project. Do you mind if I tackle this issue?

**Comment by AurelienGasser** [comment]
Hello, thank you :)

Definitely, you can have at it!

**Comment by Jamme-D** [comment]
Awesome, thanks! I'll work on it tonight.

**Comment by AurelienGasser** [comment]
@Jamme-D thanks for starting to work on this feature! I needed this feature fast so I ended up doing it. Thanks again.

**Comment by AurelienGasser** [comment]
Closed by https://github.com/AurelienGasser/planetocd/commit/b701ee99c13d713bb6c60f1b1cedf9033fc682b8
